---
--- 基本语法
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by linjw.
--- DateTime: 2019/10/31 15:33
---

-- 打印
print("Hello World!")

--[[
    全局变量, 默认情况, 变量总是认为是全局的
    全局变量不需要声明, 给一个变量赋值后即创建了全局变量
    访问没有初始化的全局变量也不会出错, 得到结果是: nil
    删除全局变量, 仅需要将变量赋值为nil
    当且仅当一个变量不等于nil时, 该变量即存在
]]
print(b)
b=10
print(b)
b=nil
print(b)