---
--- 数据类型
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by linjw.
--- DateTime: 2019/10/31 15:43
---

--[[
    Lua是动态类型语言, 不需要类型定义, 仅需要为变量赋值.
    8个基本类型: nil, boolean, number, string, userdata, function, thread, table
    nil: 表示一个无效值
    boolean: true/false
    number: 双精度类型的实浮点数
    string: 字符串由一对双引号或单引号来表示
    function: 由C或Lua编写的函数
    userdata: 任意存储在变量中的C数据结构
    thread: 执行的独立线路, 用于执行同程序
    table: Luaz中的表(table)其实是一个"关联数组", 数组的索引可以是数字, 字符串或表类型. table的创建是通过"构造表达式"来完成
]]

-- nil(空)
--[[
    对于全局变量和table, nil还有一个"删除作用"
]]
tab1 = { key1 = "val1", key2 = "val2", "val3" }
for i, v in pairs(tab1) do
    print(i .. "-" .. v)
end
print("---------分割线---------")
tab1.key1 = nil
for i, v in pairs(tab1) do
    print(i .. "-" .. v)
end
print("------------------------")
-- nil作比较时应加上双引号
print("type(X): " .. type(X))
print("type(X)==nil: " .. type(X) == nil)
print("type(X)=='nil': " .. type(X) == 'nil')

print("-------------分割线---------------")

-- boolean(布尔)
--[[
    Lua将false和nil看作是"假", 其他的都是"真"
]]
if false or nil then
    print("至少有一个是 true")
else
    print("false 和 nil 都是 false!")
end

print("------------分割线---------------")

-- number(数字)
--[[
    Lua默认只有一种number类型--double(双精度)类型(默认类型可以修改luaconf.h里的定义)
]]
-- string(字符串)
--[[
    字符串由一对双引号或单引号来表示
    也可以用2个方括号"[[/]/]"来表示"一块"字符串
]]

html = [[
    <html>
    <head></head>
    <body><a href="http://www.baidu.com">百度</a></body>
    </html>
]]
print(html)

-- 在对一个数字字符串上进行算术操作时, Lua会尝试将这个数字字符串转成一个数字
print("-- 在对一个数字字符串上进行算术操作时, Lua会尝试将这个数字字符串转成一个数字")
print("2" + 6)
print("2" + "6")
print("2 + 6")
print("-2e2" * "6")

-- Lua中字符串连接使用的是 ..
print("-- Lua中字符串连接使用的是 ..")
print("a" .. "b")

-- 使用#来计算字符串的长度, 放在字符串前面
print("-- 使用#来计算字符串的长度, 放在字符串前面")
len = "www.baidu.com"
print(#len)
print(#"www.baidu.com")

print("--------分割线----------")
-- table(表)
--[[
    table的创建是通过"构造表达式"来完成, 最简单构造表达式是{}, 用来创建一个空表. 也可以在表里添加一些数据, 直接初始化表
    是一个"关联数组"(associative arrays)", 数组的索引可以是数字或者是字符串
    不同于其他语言的数组把0作为数组的初始索引, 在Lua里表的默认初始索引一般以1开始
    不会固定长度, 有新数据添加时, table长度会自动增长, 没初始的table都是nil
]]