---
--- 变量
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by linjw.
--- DateTime: 2019/11/4 17:10
---

--[[
    Lua变量有三种类型: 全局变量、局部变量、表中的域
    Lua中的变量全是全局变量, 语句块或是函数里, 除非用local显示声明为局部变量
    局部变量的作用域为从声明位置开始到所在语句块结束
]]

-- 赋值语句
--赋值是改变一个变量的值和改变表域的最基本的方法
a = "hello" .. "world"
print("a:" .. a)
t = {}
t["n"] = 1
t["m"] = 2
t["l"] = 3
t.n = t.n + 1
for i, v in pairs(t) do
    print(i .. ":" .. v)
end

--Lua可以对多个变量同时赋值, 变量列表和值列表的各个元素用逗号分开, 赋值语句右边的值会依次赋给左边的变量
a, b = 10, 2 * 3
print("a:" .. a)
print("b:" .. b)

--遇到赋值语句Lua会先计算右边所有的值然后再执行赋值操作, 所以我们可以如此进行交换变量的值
x = 100
y = 200
print("交换前, x:" .. x .. ", y:" .. y)
x, y = y, x
print("交换后, x:" .. x .. ", y:" .. y)